In [1]:
import numpy as np


In [30]:
a1=np.array([1,2,3])
print(a1)
print(a1.shape)
print(a1.ndim)

[1 2 3]
(3,)
1


In [29]:
a2=np.array([[1,2,3],[4,5,6]])
print(a2)
print(a2.shape)
print(a2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [11]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a3)
print(a3.shape)
print(a3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)
3


In [12]:
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [10]:
np.arange(5,1,-1)

array([5, 4, 3, 2])

In [23]:
no=np.ones((2,3),dtype=int)
print(no.ndim)
print(no)

2
[[1 1 1]
 [1 1 1]]


In [21]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [28]:
np.full((3,2),5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [37]:
np.linspace(1,3,num=5,dtype=float)

array([1. , 1.5, 2. , 2.5, 3. ])

In [46]:
x=np.random.randint(1,100)
print(x)
print(np.ndim(x))

63
0


In [49]:
num=np.random.randint(1,100,size=(10,))
print(num)

[43 36 55 52 99 32 79 19 45  9]


In [51]:
num1=np.argmax(num)
num2=np.argmin(num)

print(num1)
print(num2)

4
9


In [2]:
np.random.randn(2)

array([0.49621151, 1.72165087])

In [4]:
#TASK C1: PASS/FAIL MAPPING 
#CREATE A STATUS MATRIX WHERE:
#MARK>=50 IS 1 PASS
#MARK<50 IS 0 FAIL

In [5]:
matrix=[
    ["Name","Marks","Status"],
    ["Ram",78,1],
    ["HArsh",44,0]
]

In [8]:
data=np.array(matrix)
data


array([['Name', 'Marks', 'Status'],
       ['Ram', '78', '1'],
       ['HArsh', '44', '0']], dtype='<U21')