In [ ]:
!pip install numpy

In [ ]:
import numpy as np

Creating Arrays

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


2D Array (Matrix)

In [ ]:
mat = np.array([[1,2,3],[4,5,6],[56,7,8,]])

In [ ]:
mat = np.array([[1, 2, 3],
                [4, 5, 6]])
print(mat)


[[1 2 3]
 [4 5 6]]


Using Built-in NumPy Functions

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Range of Numbers

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

Evenly Spaced Numbers

In [ ]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Array Properties

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])


In [ ]:
print(arr.ndim)    # Dimension
print(arr.shape)   # Rows, Columns
print(arr.size)    # Total elements
print(arr.dtype)

2
(2, 3)
6
int64


Data Types

In [ ]:
arr = np.array([1, 2, 3])
print(arr.dtype)


int64


Type Conversion

In [ ]:
arr = np.array([1.2, 2.5, 3.7])
arr_int = arr.astype(int)
print(arr_int)


[1 2 3]


Indexing & Slicing

In [ ]:
arr = np.array([10, 20, 30, 40])

print(arr[0])#indexing
print(arr[-1])


10
40


1D Slicing

In [ ]:
print(arr[1:3])
print(arr[:2])
print(arr[::2])


[20 30]
[10 20]
[10 30]


2D Indexing

In [ ]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(mat[0, 1])
print(mat[1])


2
[4 5 6]


In [ ]:
print(mat[:, 1])      #  column 1



[2 5 8]


In [ ]:
a = np.array([1,2,3])
b = a.copy()#copy
b[0] = 99
print(a)
print(b)


[1 2 3]
[99  2  3]


In [ ]:
a = np.array([1,2,3])
b = a # this logic is not safe
b[0] = 99
print(a)


[99  2  3]


Basic Array Operations (VECTOR POWER)

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Scalar Operations

In [ ]:
print(a + 10)
print(a * 2)


[11 12 13]
[2 4 6]


unfus (universal functions)

In [ ]:
arr = np.array([1,4,9,16])

print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))


[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
16
1
7.5
30
5.678908345800274


Boolean Indexing

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 25])


[30 40 50]


In [ ]:
print(arr>25)

[False False  True  True  True]


Broadcasting Rule

In [ ]:
#NumPy automatically expands smaller arrays

In [ ]:
arr = np.array([1,2,3,4])
print(arr + 10)


[11 12 13 14]


In [ ]:
mat = np.array([[1,2,3],
                [4,5,6]])

print(mat + 10)


[[11 12 13]
 [14 15 16]]


In [ ]:
row = np.array([1,2,3])
print(mat + row)


[[2 4 6]
 [5 7 9]]


Matrix Multiplication

In [ ]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(np.dot(A, B))


[[19 22]
 [43 50]]


In [ ]:
print(A.T)#transpose


[[1 3]
 [2 4]]


Random Module

In [ ]:
np.random.rand(5)



array([0.72376067, 0.10774613, 0.38657665, 0.6852319 , 0.32281983])

In [ ]:
np.random.rand(3,3)

array([[0.80447729, 0.83133116, 0.39884793],
       [0.25091164, 0.89470072, 0.0501089 ],
       [0.58180054, 0.22589793, 0.57313604]])

In [ ]:
np.random.randint(1, 100, 10)


array([50, 41, 49, 36, 95, 20, 45, 56, 14,  4])

Reshaping Arrays

In [ ]:
arr = np.arange(12)
print(arr.reshape(3,4))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


axis in NumPy

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [ ]:
print(np.sum(arr))


21


In [ ]:
print(np.sum(arr, axis=0))   # column-wise


[5 7 9]


In [ ]:
print(np.sum(arr, axis=1))   # row-wise


[ 6 15]


Where in numpy

In [2]:
arr = np.array([10, -5, 20, -3, 15])


In [1]:
import numpy as np

In [3]:
print(arr<5)

[False  True False  True False]


In [ ]:
result = np.where(arr < 0, 0, arr)
print(result)


[10  0 20  0 15]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])


In [ ]:
result = np.where(arr % 2 != 0, -1, arr)
print(result)


[-1  2 -1  4 -1]


In [ ]:
marks = np.array([45, 78, 32, 90, 55])


In [ ]:
status = np.where(marks >= 50, 1, 0)
print(status)


[0 1 0 1 1]


In [ ]:
data = np.array([10, 20, 30, 40, 50])


In [ ]:
mean_val = np.mean(data)
result = np.where(data > mean_val, mean_val, data)
print(result)


[10. 20. 30. 30. 30.]


applying (where) condition in 2d array

In [ ]:
mat = np.array([
    [10, 60, 30],
    [80, 20, 90]
])


In [ ]:
result = np.where(mat >= 50, 1, 0)
print(result)


[[0 1 0]
 [1 0 1]]
